import { useEffect, useState } from "react";

import Loader from "@/components/Loader";
import Card from "@/components/Card";

export default function Home() {
  const [Loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([]);
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    setLoading(true);
    (async () => {
      try {
        const data = await fetch("api/posts").then((res) => res.json());
        if (data?.posts[0]) {
          setAllPosts(data.posts);
          setPosts(data.posts);
        }
      } catch (err) {
        alert("An error occurred while loading the posts");
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  function search({ target }) {
    if (target.value.toLowerCase() === "") {
      setPosts(allPosts);
    } else {
      const searchResults = posts.filter((post) =>
        post.prompt.toLowerCase().includes(target.value.toLowerCase())
      );

      setPosts(searchResults);
    }
  }

  return (
    <div className="home content">
      <div className="container">
        <h1 className="title">the community showcase</h1>
        <p className="text">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
        <div className="text-input">
          <label htmlFor="posts-search">Search posts</label>
          <input
            onChange={search}
            type="text"
            id="posts-search"
            placeholder="Search something..."
          />
        </div>
        {!Loading ? (
          <div className="cards">
            {posts[0] ? (
              posts.map((post) => {
                return <Card key={post._id} post={post}></Card>;
              })
            ) : (
              <p className="not-found">No posts found</p>
            )}
          </div>
        ) : (
          <Loader></Loader>
        )}
      </div>
    </div>
  );
}
